# NumPy

Read the link https://numpy.org/doc/stable/user/quickstart.html before starting the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [2]:
A = np.arange(1, 16).reshape(3,5)

A.ndim


2

In [3]:
A.shape

(3, 5)

In [4]:
type(A)

numpy.ndarray

In [5]:
A.size

15

### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [7]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

print(B*C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]


In [8]:
print(B@C)

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on matrix D:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [9]:
D = np.arange(1, 10).reshape(3, 3)
print(D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
np.exp(D)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [12]:
print('Minium value')
print(D.min())
print()
print('Index for the mimimum value')
print(np.argmin(D))

Minium value
1

Index for the mimimum value
0


In [13]:
print('Lowest value for each row')
print(D.min(axis=1))

print()
print('Minimum index in each row')
print(np.argmin(D, axis=1))

Lowest value for each row
[1 4 7]

Minimum index in each row
[0 0 0]


In [15]:
print("Minimum value in each column")
D.min(axis=0)

Minimum value in each column


array([1, 2, 3])

In [16]:
print("Mimum index  in each column")
np.argmin(D, axis=1)

Mimum index  in each column


array([0, 0, 0])

In [17]:
np.argmin(D)

np.int64(0)

In [20]:
D.sum()

np.int64(45)

In [21]:
D.mean(axis=0)

array([4., 5., 6.])

In [22]:
np.median(D, axis=0)

array([4., 5., 6.])

### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [58]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [62]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [ ]:
The result will be the rowline that you specified. That is row number one which is indexed by 0 and now row number 2 which is indexed by the number 1. 

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [23]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [24]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [25]:
print('Iterating over a multidimensionel array elementwise')
for i in np.nditer(A):
    print(i)

Iterating over a multidimensionel array elementwise
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [26]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [28]:
print("Turning and reshaping a 30 element 1 dimensionell array to a 3D array with 2 arrays with 3 arrays inside and letting pyton figure out the next dimension with using the -1 as the 3rd element.")

Turning and reshaping a 30 element 1 dimensionell array to a 3D array with 2 arrays with 3 arrays inside and letting pyton figure out the next dimension with using the -1 as the 3rd element.


### Broadcasting
Read the link https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting and the document *"matematik_yh_kap_10"* (solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh) before starting the exercises below.  

If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

##### Remark on Broadcasting when doing Linear Algebra calculations in Python. 
From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices.

In [29]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [30]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [31]:
A = np.arange(1, 5).reshape(2,2)
print(A)
print()
b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]

[2 2]


### Vector and matrix algebra

Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.

Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).

In [32]:
import numpy as np

def add_mult_matrices(A, B, operation):
    """
    Add or multiply two matrices using NumPy with validation.


    Returns
    -------
    numpy.ndarray
        Result of the matrix addition or multiplication
    """

    # Validate input types
    if not isinstance(A, np.ndarray) or not isinstance(B, np.ndarray):
        raise TypeError("Both A and B must be numpy.ndarray objects.")

    # Validate operation argument
    if operation not in ("add", "multiply"):
        raise ValueError("Operation must be either 'add' or 'multiply'.")

    # Matrix addition
    if operation == "add":
        if A.shape != B.shape:
            raise ValueError(
                "For matrix addition, both matrices must have the same shape."
            )
        print(A + B) 

    # Matrix multiplication
    if operation == "multiply":
        if A.shape[1] != B.shape[0]:
            raise ValueError(
                "For matrix multiplication, the number of columns in A "
                "must equal the number of rows in B."
            )
        print(A @ B) 

In [33]:
E = np.arange(1, 5).reshape(2,2)
F = np.arange(0, 4).reshape(2,2)

print('adding')
add_mult_matrices(E, F, 'add')
print()
print('Multiply')
add_mult_matrices(E, F, 'multiply')



adding
[[1 3]
 [5 7]]

Multiply
[[ 4  7]
 [ 8 15]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. Note, the function you created above can be used. 

In [34]:
X = np.array([4,3])
print(X.shape)

(2,)


In [35]:
print(5*X)

[20 15]


In [36]:
print(3*X)

[12  9]


In [37]:
print(5*X + 3*X)

[32 24]


In [38]:
print(8*X)

[32 24]


In [39]:
print(4*X -X)

[12  9]


In [41]:
Y = X.transpose()
print(Y)
print(Y.shape)


[4 3]
(2,)


In [42]:
X+Y

array([8, 6])

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

In [43]:
A = np.array([[2, 1, -1],
              [1, -1, 1]])

B = np.array([[4, -2, 1],
              [2, -4, -2]])

C = np.array([[1, 2],
              [2, 1]])
D = np.array([[3, 4],
              [4, 3]])
E = np.array([[1],
              [2]])
I = np.array([[1, 0],
              [0, 1]])

In [50]:
print(2*A)

[[ 4  2 -2]
 [ 2 -2  2]]


In [51]:
print(B-2*A)

[[ 0 -4  3]
 [ 0 -2 -4]]


In [52]:
print(3*C - 2*E)

[[ 1  4]
 [ 2 -1]]


In [53]:
print(2*D -3*C)

[[3 2]
 [2 3]]


In [48]:
print(2*D -3*C)

[[3 2]
 [2 3]]


In [49]:
print(D.T + 2*D)

[[ 9 12]
 [12  9]]


In [54]:
print(2*C.T - 2*D.T)

[[-4 -4]
 [-4 -4]]


In [46]:
print('A.T - B is not defined')

A.T - B is not defined


In [57]:

A@C

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [58]:
print(C@D)

[[11 10]
 [10 11]]


In [59]:
print(C@B)

[[  8 -10  -3]
 [ 10  -8   0]]


In [60]:
print(C@I)

[[1 2]
 [2 1]]


In [61]:
print(C@B.T)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [62]:
A = np.array([[2, 3, 4],
              [5, 4, 1]])

In [63]:
print(' Task 10.2.2')
print(A@A.T)

 Task 10.2.2
[[29 26]
 [26 42]]


In [64]:
print(' Task 10.2.3')
A = np.array([[1, 2],
              [2, 4]])

B = np.array([[2, 1],
              [1, 3]])

C = np.array([[4, 3],
              [0, 2]])

 Task 10.2.3


In [65]:
print('AB')
print(A@B)
print()
print('AC')
print(A@C)
print()
print('AB is equal to AC?')
print(A@B == A@C)


AB
[[ 4  7]
 [ 8 14]]

AC
[[ 4  7]
 [ 8 14]]

AB is equal to AC?
[[ True  True]
 [ True  True]]


In [66]:
print('B is equal to C?')
print(B==C)

B is equal to C?
[[False False]
 [False False]]


### Copies and Views
Read the link https://numpy.org/doc/stable/user/basics.copies.html before starting the exercises below. 

Basic indexing creates a view. How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?

In [68]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [69]:
print("Is v2 a view or copyt")
print("if True, v2 is a view , if False v2 is a copy")
v2.base is v1

Is v2 a view or copyt
if True, v2 is a view , if False v2 is a copy


True

In [70]:
print("Change last element in v1 to 9")
v1[-1] = 9
print(v1)
print(v2)
print()
print("Change the last element in v2 to 123")
v2[-1] = 123
print(v2)
print(v1)


Change last element in v1 to 9
[0 1 2 9]
[2 9]

Change the last element in v2 to 123
[  2 123]
[  0   1   2 123]


In [71]:
print("if v1 and v2 are True in this function shares the same memory means view, If false they are copies")
np.shares_memory(v1, v2)

if v1 and v2 are True in this function shares the same memory means view, If false they are copies


True

In [72]:
print("v2 was changed and because v1 also changed which means view")
print(v1)

v2 was changed and because v1 also changed which means view
[  0   1   2 123]
